name: msbuild-o-dh-010

on:
  push:
    branches:
      - main # Kích hoạt workflow khi đẩy lên nhánh main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: msbuild-o-dh-010
    # Set environment variables for the entire job
    env:
      OAESFILE: ${{ secrets.OAESFILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Git ls-tree
        if: always()
        shell: pwsh
        run: ./.github/scripts-yml/git-ls-tree.ps1

      - name: Upload build artifacts v4
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/ # Tải lên thư mục build (dist)
          retention-days: 10 # Định nghĩa thời gian tồn tại (ở đây là 30 ngày)
          compression-level: 9 # maximum compression
